import "./globals.css";
import MainProvider from "./providers/MainProvider";
import ScrollTop from "@/components/ScrollTop";
import Topheader from "@/components/Topheader";
import HeaderWrapper from "@/components/HeaderWrapper"; // ✅ FIX
import MenuCategory from "@/components/MenuCategory";
import Footer from "@/components/Footer";
import { SearchProvider } from "@/app/context/SearchContext";

export const metadata = { 
  title: { 
    template: "%s ", 
    default: "" 
  }, 
  description: "Generated by create next app", 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <MainProvider>
          <SearchProvider>

            <ScrollTop />
            <Topheader />

            <HeaderWrapper /> {/* ✅ FIXED */}

            <MenuCategory />
            {children}
            <Footer />

          </SearchProvider>
        </MainProvider>

      </body>
    </html>
  );
}