import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topheader from "@/components/Topheader";
import Header from "@/components/Header";
import MenuCategory from "@/components/MenuCategory";
import Footer from "@/components/Footer";
import ScrollTop from "@/components/ScrollTop";
import { CartProvider } from "./context/CartContext";
import { WishlistProvider } from "@/app/context/WishlistContext"
import { Toaster } from "react-hot-toast"

export const metadata = {
  title: {
    template: "%s ",
    default: ""
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ScrollTop />
        <CartProvider> 
          <Topheader />
          <Header />
          <MenuCategory />
          <WishlistProvider>
            <Toaster position="top-right" />
            {children}
          </WishlistProvider>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}