import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topheader from "@/components/Topheader";
import Header from "@/components/Header";
import MenuCategory from "@/components/MenuCategory";
import Footer from "@/components/Footer";
import ScrollTop from "@/components/ScrollTop";
import { CartProvider } from "./context/CartContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template : "%s ",
    default: ""
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ScrollTop />
        <Topheader />
        <MenuCategory/>
        <CartProvider>
        <Header/>
        {children}  
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}


